Repository Team-BSUCC/moram-moram, pull requests merged in 2025-04, with the labels that each got.

#23 feature:#7 Button 컴포넌트 생성 및 기능구현
  src/components/commons/Button.tsx
Labels: 🔧Feature, 💐Style

#25 feature:#10 Text 컴포넌트 생성 및 기능구현
  src/components/commons/Text.tsx
Labels: 🔧Feature, 💐Style

#29 feature:#17 commons/CheckBox 컴포넌트 생성 및 기능구현
  src/components/commons/check-box.tsx
Labels: 🔧Feature

#28 Feature/#9 common input
  src/components/commons/input.tsx
Labels: 🔧Feature

#27 Feature/#8 common title
  src/components/commons/title.tsx
Labels: 🔧Feature, 💐Style

#26 feature:#11 commons/Spacer 컴포넌트 생성 및 기능구현
  src/components/commons/Spacer.tsx
Labels: 🔧Feature, 💐Style

#37 Feature/#11 common spacer
  src/components/commons/.gitkeep
  src/components/commons/spacer.tsx
Labels: 🏃Move

#24 feature:#18 commons/round-button 컴포넌트 생성 및 기능구현
  src/components/commons/round-button.tsx
Labels: 🔧Feature, 💐Style

#39 feature:#15 commons/circularProgress 컴포넌트 생성 및 기능구현
  package.json
  pnpm-lock.yaml
  src/components/commons/circular-progress.tsx
Labels: 🔧Feature, 💐Style

#40 feature:#16 commons/LinearProgress 컴포넌트 생성 및 기능구현
  src/components/commons/progress-bar.tsx
Labels: 🔧Feature, 💐Style

#43 Style/#41 global style
  public/fonts/pretendard-variable.woff2
  src/app/layout.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 📁Add, 📜Chore, 💐Style

#42 Feature/#6 common components
  package.json
  pnpm-lock.yaml
  src/components/commons/.gitkeep
  src/components/commons/button.tsx
  src/components/commons/check-box.tsx
  src/components/commons/circular-progress.tsx
  src/components/commons/input.tsx
  src/components/commons/progress-bar.tsx
  src/components/commons/round-button.tsx
  src/components/commons/spacer.tsx
  src/components/commons/text.tsx
  src/components/commons/title.tsx
Labels: 🔧Feature, 💐Style

#36 chore#35 수파베이스 타입 파일 생성
  .eslintignore
  package.json
  src/shared/types/database.types.ts
Labels: 📜Chore

#32 Feature/#22 floating sheet
  package.json
  pnpm-lock.yaml
  src/components/commons/floating-sheet.tsx
Labels: 🔧Feature

#44 Feature/#12 layout
  src/app/layout.tsx
Labels: 🔧Feature, 💐Style

#56 Feature/#50 realtime batch save
  src/modules/mandalart/hooks/.gitkeep
  src/modules/mandalart/hooks/use-realtime-broadcast-batch.ts
  src/modules/mandalart/services/.gitkeep
  src/modules/mandalart/services/mandalart-batch-update-supabase-service.ts
  src/modules/mandalart/types/realtime-type.ts
Labels: 📁Add, 🔧Feature

#55 Feature/#48 셀 컴포넌트 생성 & 초기 데이터 로딩
  src/app/mandalart/.gitkeep
  src/app/mandalart/page.tsx
  src/components/commons/floating-sheet.tsx
  src/modules/mandalart/components/.gitkeep
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/register-todo.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
  src/modules/mandalart/services/fetch-get-mandalarts-data.ts
  src/modules/mandalart/services/get-data-category.ts
  src/modules/mandalart/types/realtime-type.ts
  src/shared/constants/query-key.ts
  src/shared/hooks/use-floating-sheet-store.ts
Labels: 🔧Feature, 🏠Refactor

#57 Feature/#49 share realtime state
  src/modules/mandalart/hooks/use-edit-mutation.ts
  src/modules/mandalart/services/broadcast-event-sender.ts
  src/modules/mandalart/services/process-query-key.ts
  src/modules/mandalart/services/throttle-mutate.ts
Labels: 🔧Feature

#59 Feature/#51 RealtimeRoom 컴포넌트 추가 및 사용자 정보 처리 로직 구현
  src/modules/dashboard/components/.gitkeep
  src/modules/dashboard/components/realtime-room.tsx
Labels: 🔧Feature

#62 Feature/#60 realtime batch update upgrade
  src/modules/mandalart/hooks/use-batch-update-trigger.ts
  src/modules/mandalart/hooks/use-broadcast-store.ts
  src/modules/mandalart/hooks/use-realtime-broadcast-batch.ts
  src/modules/mandalart/hooks/use-receive-broadcast-store.ts
  src/modules/mandalart/services/mandalart-batch-update-supabase-service.ts
  src/modules/mandalart/types/realtime-type.ts
Labels: 🔧Feature, 🏠Refactor

#61 Feature/#34 realtime avatar
  package.json
  pnpm-lock.yaml
  src/components/ui/avatar.tsx
  src/components/ui/tooltip.tsx
  src/modules/mandalart/components/avatar-stack.tsx
  src/modules/mandalart/components/realtime-avatar-stack.tsx
  src/modules/mandalart/hooks/use-current-user-image.ts
  src/modules/mandalart/hooks/use-current-user-name.ts
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
Labels: 🔧Feature

#63 Feature/#48 realtime domain cell
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
Labels: 🔧Feature, 🏠Refactor

#66 Feature/#34 realtime avatar
  src/app/mandalart/page.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/realtime-avatar-stack.tsx
  src/modules/mandalart/hooks/use-current-user-name.ts
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
Labels: 🔧Feature, 🏠Refactor

#68 Refactor/#67 realtime feature consolidation
  src/app/mandalart/page.tsx
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/cursor.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/realtime-avatar-stack.tsx
  src/modules/mandalart/components/realtime-cursors.tsx
  src/modules/mandalart/components/register-todo.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/hooks/use-batch-update-trigger.ts
  src/modules/mandalart/hooks/use-broadcast-mutation.ts
  src/modules/mandalart/hooks/use-current-user-id.ts
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
  src/modules/mandalart/hooks/use-realtime-user-sync.ts
  src/modules/mandalart/services/broadcast-event-sender.ts
  src/modules/mandalart/services/get-data-category.ts
  src/modules/mandalart/services/mandalart-batch-update-supabase-service.ts
  src/modules/mandalart/services/process-query-key.ts
  src/modules/mandalart/types/realtime-type.ts
  src/shared/constants/query-key.ts
  src/shared/hooks/use-floating-sheet-store.ts
Labels: 🧹Clean Up, 🏠Refactor

#69 refactor:#60 배치업데이트 시점 수정 쓰로틀링, 브로드캐스트 요청에만 적용되게 수정 및 훅으로 변경
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/hooks/use-batch-update-trigger.ts
  src/modules/mandalart/hooks/use-broadcast-mutation.ts
  src/modules/mandalart/hooks/use-broadcast-store.ts
  src/modules/mandalart/hooks/use-throttle-mutate.ts
Labels: 🏠Refactor

#71 Feature/#65 todo crud
  src/app/mandalart/page.tsx
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/register-todo.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
  src/modules/mandalart/hooks/use-todo-broadcast-mutation.ts
  src/modules/mandalart/services/create-new-todo-row-value.ts
  src/modules/mandalart/services/create-todo-list-key.ts
  src/modules/mandalart/services/judging-action.ts
  src/shared/constants/query-key.ts
Labels: 🔧Feature, 🏠Refactor

#81 Feature/#60 realtime batch update upgrade
  src/app/mandalart/page.tsx
  src/modules/mandalart/hooks/use-todo-broadcast-mutation.ts
  src/modules/mandalart/services/mandalart-batch-update-supabase-service.ts
Labels: 🔧Feature

#79 Feature/#73 calendar UI
  package.json
  pnpm-lock.yaml
  src/app/calendar/page.tsx
  src/components/commons/floating-sheet.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/type/todo-type.ts
  src/shared/hooks/use-floating-sheet-store.ts
  src/styles/calendar-custom.css
Labels: 🔧Feature, 💐Style

#82 Bugfix/#76 로그인 시 새로고침 후 적용되는 버그 해결
  src/app/(auth)/api/refresh/route.ts
  src/app/(auth)/api/sign-in/route.ts
  src/app/(auth)/api/sign-out/route.ts
  src/modules/auth/hooks/use-sign-in-form.ts
  src/modules/auth/services/auth-server-service.ts
Labels: 🕷️BugFix, 🏠Refactor

#89 Feature/#72 realtime data sender
  src/app/mandalart/page.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
  src/modules/mandalart/hooks/use-receive-broadcast-store.ts
Labels: 🔧Feature

#90 Feature/#45 realtime domain
  .eslintrc.json
  components.json
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/mandalart/.gitkeep
  src/app/mandalart/page.tsx
  src/components/commons/floating-sheet.tsx
  src/components/ui/avatar.tsx
  src/components/ui/tooltip.tsx
  src/lib/utils.ts
  src/modules/dashboard/components/.gitkeep
  src/modules/dashboard/components/realtime-room.tsx
  src/modules/mandalart/components/.gitkeep
  src/modules/mandalart/components/avatar-stack.tsx
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/cursor.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/realtime-avatar-stack.tsx
  src/modules/mandalart/components/realtime-cursors.tsx
  src/modules/mandalart/components/register-todo.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/hooks/.gitkeep
  src/modules/mandalart/hooks/use-batch-update-trigger.ts
  src/modules/mandalart/hooks/use-broadcast-mutation.ts
  src/modules/mandalart/hooks/use-broadcast-store.ts
  src/modules/mandalart/hooks/use-current-user-id.ts
  src/modules/mandalart/hooks/use-current-user-image.ts
  src/modules/mandalart/hooks/use-current-user-name.ts
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
  src/modules/mandalart/hooks/use-realtime-cursors.ts
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
  src/modules/mandalart/hooks/use-realtime-user-sync.ts
  src/modules/mandalart/hooks/use-receive-broadcast-store.ts
  src/modules/mandalart/hooks/use-throttle-mutate.ts
  src/modules/mandalart/hooks/use-todo-broadcast-mutation.ts
  src/modules/mandalart/services/.gitkeep
  src/modules/mandalart/services/create-new-todo-row-value.ts
  src/modules/mandalart/services/create-todo-list-key.ts
  src/modules/mandalart/services/fetch-get-mandalarts-data.ts
  src/modules/mandalart/services/get-data-category.ts
  src/modules/mandalart/services/judging-action.ts
  src/modules/mandalart/services/mandalart-batch-update-supabase-service.ts
  src/modules/mandalart/services/process-query-key.ts
  src/modules/mandalart/types/.gitkeep
  src/modules/mandalart/types/realtime-type.ts
  src/providers/.gitkeep
  src/providers/tq-provider.tsx
  src/shared/constants/query-key.ts
  src/shared/hooks/use-floating-sheet-store.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 📁Add, 🔧Feature

#87 Feature/#83 calendar data fetch
  src/app/calendar/page.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/hooks/use-fetch-calendar-query.ts
  src/modules/calendar/services/.gitkeep
  src/modules/calendar/type/fetch-calendar-type.ts
  src/modules/calendar/type/todo-type.ts
  src/shared/api/get-all-mandalart-data.ts
  src/styles/calendar-custom.css
Labels: 🔧Feature, 🏠Refactor

#84 Feature/#58 guest domain
  package.json
  pnpm-lock.yaml
  src/app/(non-auth)/guest/page.tsx
  src/modules/guest/components/guest-mandalart-block.tsx
  src/modules/guest/components/guest-mandalart-cell.tsx
  src/modules/guest/components/guest-mandalart-main-block.tsx
  src/modules/guest/hooks/.gitkeep
  src/modules/guest/hooks/use-guest-topic-store.ts
  src/modules/guest/services/.gitkeep
  src/modules/guest/types/.gitkeep
  src/modules/studio/services/.gitkeep
  src/modules/studio/types/.gitkeep
  src/shared/utils/get-color-with-number.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🔧Feature, 💐Style

#94 Refactor:#83 my-mandalarts API 추가 및 공용 폴더로 이동
  src/app/api/my-mandalarts/route.ts
  src/app/calendar/page.tsx
  src/modules/calendar/hooks/use-fetch-calendar-query.ts
  src/shared/hooks/use-get-my-mandalarts-query.ts
Labels: 🏠Refactor

#95 Feature/#75 calendar domain
  package.json
  pnpm-lock.yaml
  src/app/api/my-mandalarts/route.ts
  src/app/calendar/page.tsx
  src/components/commons/floating-sheet.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/services/.gitkeep
  src/modules/calendar/type/fetch-calendar-type.ts
  src/modules/calendar/type/todo-type.ts
  src/shared/hooks/use-floating-sheet-store.ts
  src/shared/hooks/use-get-my-mandalarts-query.ts
  src/styles/calendar-custom.css
Labels: 🔧Feature, 💐Style

#96 Feature/#86 dashboard domain
  src/app/dashboard/.gitkeep
  src/app/dashboard/page.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
  src/modules/dashboard/components/mandalart-card.tsx
  src/modules/dashboard/components/realtime-room.tsx
  src/modules/dashboard/services/.gitkeep
  src/shared/utils/calculator-progress.ts
  src/shared/utils/format-date.ts
Labels: 🔧Feature, 💐Style

#101 Bugfix/#98 인증 리디렉션 로직 간소화
  src/app/(auth)/api/callback/route.ts
Labels: 🕷️BugFix

#103 Style:#75 플로팅 시트에 여백 추가 및 버튼 스타일 수정
  src/components/commons/floating-sheet.tsx
Labels: 💐Style

#102 Style/#91 mandalart cell UI
  src/app/mandalart/page.tsx
  src/components/commons/progress-bar.tsx
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/modules/mandalart/services/fetch-get-mandalarts-data.ts
  src/modules/mandalart/types/realtime-type.ts
  tailwind.config.ts
Labels: 💐Style

#85 Feature/#77 홈 페이지 구성 요소 추가
  package.json
  pnpm-lock.yaml
  public/images/calendar/calendar.png
  public/images/hero/landing-img-hero.png
  public/images/intro/arrow.png
  public/images/intro/background.png
  public/images/intro/otani-mandalart.png
  public/images/intro/otani.png
  public/images/mandalart/ai-icon.png
  public/images/mandalart/mandalart-block.png
  public/images/progress/0.png
  public/images/progress/100.png
  public/images/progress/30.png
  public/images/progress/60.png
  public/images/progress/background.png
  public/images/progress/progress.png
  public/images/team/team-explain.png
  public/images/todo/todo.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/commons/button.tsx
  src/components/landing/animated-section.tsx
  src/components/landing/calendar-section.tsx
  src/components/landing/cta-section.tsx
  src/components/landing/hero-section.tsx
  src/components/landing/intro-sercion.tsx
  src/components/landing/mandalart-explain-section.tsx
  src/components/landing/progress-section.tsx
  src/components/landing/scroll-top.tsx
  src/components/landing/team-planning-section.tsx
  src/components/landing/todo-editor-section.tsx
Labels: 🔧Feature

#100 Style/#93 todo layout
  src/app/today-list/page.tsx
Labels: 🔧Feature, 💐Style

#104 Style/#91 mandalart todo UI
  src/components/commons/input.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/types/realtime-type.ts
Labels: 💐Style

#105 Feature/#75 calendar domain
  src/app/calendar/page.tsx
  src/components/commons/floating-sheet.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/calendar-todo-item.tsx
  src/modules/calendar/services/.gitkeep
  src/modules/calendar/services/get-processed-date.ts
  src/modules/calendar/type/todo-type.ts
  src/styles/calendar-custom.css
Labels: 🏠Refactor, 💐Style

#108 Feature/#107 footer
  public/images/github-logo.svg
  public/images/manda-log-text-.svg
  public/images/manda-logo.svg
  public/images/palms-logo.svg
  src/app/layout.tsx
  src/components/layouts/footer.tsx
Labels: 🔧Feature, 💐Style

#110 Style/#106 header style
  public/images/manda-logo-text.svg
  src/app/calendar/page.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/components/commons/button.tsx
  src/components/layouts/.gitkeep
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
  src/modules/auth/components/sign-out-button.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/mandalart/components/cell.tsx
  src/shared/constants/url-constants.ts
Labels: 🔧Feature, 💐Style

#111 style:#106 헤더 백그라운드 컬러 수정 및 구분 선 추가
  src/components/layouts/header.tsx
Labels: 💐Style

#113 Feature/#92 todo domain
  src/app/today-list/page.tsx
Labels: 🔧Feature, 💐Style

#114 Bugfix/#112 social sign in error
  src/app/(auth)/api/callback/route.ts
  src/app/(auth)/api/refresh/route.ts
  src/app/(auth)/api/sign-in/route.ts
  src/app/layout.tsx
  src/components/layouts/header.tsx
  src/modules/auth/services/auth-server-service.ts
  src/shared/constants/url-constants.ts
  src/shared/utils/supabase/server-client-action.ts
Labels: 🕷️BugFix

#115 Bugfix/#112 URL 처리 방식 개선 및 주석 추가
  src/app/(auth)/api/callback/route.ts
Labels: 🕷️BugFix

#118 Bugfix/#112 social button "use client" 설정, window.location 설정
  src/app/(auth)/api/callback/route.ts
  src/app/(auth)/api/refresh/route.ts
  src/app/(auth)/api/sign-in/route.ts
  src/modules/auth/components/google-login-button.tsx
  src/modules/auth/components/kakao-login-button.tsx
  src/modules/auth/hooks/use-auto-refresh-session.ts
  src/modules/auth/hooks/use-sign-in-form.ts
  src/modules/auth/services/auth-client-service.ts
  src/shared/utils/supabase/server-client-action.ts
Labels: 🕷️BugFix

#121 Refactor/#97 common components refactor
  src/app/(non-auth)/guest/page.tsx
  src/components/commons/button.tsx
  src/components/commons/circular-progress.tsx
  src/components/commons/input.tsx
  src/components/commons/progress-bar.tsx
  src/components/commons/text.tsx
  src/components/commons/title.tsx
  src/components/landing/cta-section.tsx
  src/components/landing/hero-section.tsx
  src/modules/auth/components/sign-in-form.tsx
  src/modules/auth/components/sign-up-form.tsx
  src/modules/dashboard/components/mandalart-card.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🏠Refactor, 💐Style

#120 Feature/#75 calendar domain
  src/app/api/my-mandalarts/route.ts
  src/app/calendar/page.tsx
  src/components/commons/drop-down.tsx
  src/components/commons/floating-sheet.tsx
  src/components/commons/spacer.tsx
  src/components/commons/text.tsx
  src/components/commons/title.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/calendar-todo-item.tsx
  src/modules/calendar/hooks/use-delete-todo-mutation.ts
  src/modules/calendar/hooks/use-update-todo-mutation.ts
  src/modules/calendar/services/edit-todo-data.ts
  src/modules/calendar/services/get-processed-date.ts
  src/modules/calendar/type/fetch-calendar-type.ts
  src/modules/calendar/type/todo-type.ts
  src/modules/calendar/utils/get-processed-date.ts
  src/styles/calendar-custom.css
Labels: 🔧Feature

#127 Refactor/#126 floating sheet
  src/components/commons/floating-sheet.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
Labels: 👨‍🔧Fix, 💐Style

#128 Feature/#70 mandalart realtime invite auth
  src/app/mandalart/page.tsx
  src/components/layouts/header.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/mandalart-passcode-gate.tsx
  src/modules/mandalart/components/realtime-avatar-stack.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
  src/modules/mandalart/hooks/use-broadcast-store.ts
  src/modules/mandalart/hooks/use-current-user-id.ts
  src/modules/mandalart/hooks/use-current-user-image.ts
  src/modules/mandalart/hooks/use-current-user-name.ts
  src/modules/mandalart/hooks/use-get-room-data.ts
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
  src/modules/mandalart/hooks/use-realtime-user-sync.ts
  src/modules/mandalart/hooks/use-users-store.ts
  src/modules/mandalart/services/fetch-check-room-passcode.ts
  src/modules/mandalart/services/fetch-update-room-passcode.ts
  src/modules/mandalart/utils/check-user-join-time.ts
  src/modules/mandalart/utils/is-registered-user.ts
  src/shared/utils/.gitkeep
  src/shared/utils/get-current-user-id.ts
  src/shared/utils/get-current-user-name.ts
Labels: 🧹Clean Up, 🔧Feature, 🏠Refactor

#125 Feature/#92 todo domain
  src/app/today-list/loading.tsx
  src/app/today-list/page.tsx
  src/components/commons/drop-down.tsx
  src/components/commons/title.tsx
  src/modules/calendar/hooks/use-delete-todo-mutation.ts
  src/modules/calendar/utils/filter-by-completion-status.ts
  src/modules/calendar/utils/get-processed-date.ts
  src/modules/today-list/components/mandalart-title-tab.tsx
  src/modules/today-list/components/order-option-selection.tsx
  src/modules/today-list/components/today-todo-list.tsx
  src/modules/today-list/components/todo-item.tsx
  src/modules/today-list/types/today-list-type.ts
  src/modules/today-list/utils/flatten-todos.ts
  src/modules/today-list/utils/get-selected-label.ts
  src/modules/today-list/utils/group-by.ts
  src/shared/utils/get-color-with-number.ts
Labels: 🏠Refactor, 💐Style

#129 Refactor/#117 mandalart using common component
  src/modules/mandalart/components/cell.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/sub-block.tsx
Labels: 💐Style

#131 Feature/#75 calendar domain
  src/app/calendar/page.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/calendar-todo-item.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/calendar/hooks/use-update-todo-mutation.ts
  src/modules/calendar/services/edit-todo-data.ts
  src/modules/calendar/utils/match-with-common-color.ts
  src/modules/today-list/types/today-list-type.ts
  src/modules/today-list/utils/flatten-todos.ts
  src/shared/utils/get-color-with-index.ts
  src/styles/calendar-custom.css
Labels: 🔧Feature, 🏠Refactor

#141 Feature/#139 mandalart path parameter
  src/app/mandalart/[id]/page.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
Labels: 🔧Feature

#135 Feature/#133 sentry 설치
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: 🔧Feature

#123 Refactor/#119 refactoring with css
  public/images/calendar/calendar-mobile.png
  public/images/intro/otani-background.png
  src/app/layout.tsx
  src/components/landing/calendar-section.tsx
  src/components/landing/cta-section.tsx
  src/components/landing/hero-section.tsx
  src/components/landing/intro-sercion.tsx
  src/components/landing/mandalart-explain-section.tsx
  src/components/landing/progress-section.tsx
  src/components/landing/team-planning-section.tsx
  src/components/landing/todo-editor-section.tsx
Labels: 🏠Refactor, 💐Style

#137 Refactor/#124 refactoring auth page
  public/images/button-image/google.svg
  public/images/button-image/kakao-talk.png
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/commons/input.tsx
  src/components/commons/round-button.tsx
  src/components/commons/text.tsx
  src/modules/auth/components/google-login-button.tsx
  src/modules/auth/components/kakao-login-button.tsx
  src/modules/auth/components/sign-in-form.tsx
  src/modules/auth/components/sign-up-form.tsx
  src/modules/auth/hooks/use-sign-in-form.ts
  src/modules/auth/hooks/use-sign-up-form.ts
Labels: 🔧Feature, 🏠Refactor, 💐Style

#138 Style/#130 mandalart floating sheet style
  src/components/commons/drop-down.tsx
  src/components/commons/floating-sheet.tsx
  src/components/commons/title.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/subtopic-group.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/hooks/use-realtime-cursors.ts
Labels: 💐Style

#140 Feature/#92 todo domain
  src/app/today-list/page.tsx
  src/components/layouts/footer.tsx
  src/modules/calendar/hooks/use-delete-todo-mutation.ts
  src/modules/calendar/hooks/use-update-todo-mutation.ts
  src/modules/today-list/components/today-todo-list.tsx
  src/styles/globals.css
Labels: 👨‍🔧Fix, 💐Style

#145 style:#142 패스코드 입력창 디자인 수정
  src/modules/mandalart/components/mandalart-passcode-gate.tsx
Labels: 💐Style

#143 Feature/#86 dashboard domain
  src/app/api/dashboard/route.ts
  src/app/dashboard/page.tsx
  src/components/commons/input.tsx
  src/components/commons/title.tsx
  src/modules/dashboard/components/calendar-drop-down.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
  src/modules/dashboard/components/color-picker.tsx
  src/modules/dashboard/components/create-mandalart-modal.tsx
  src/modules/dashboard/components/dashboard-avatar-stack.tsx
  src/modules/dashboard/components/dashboard.tsx
  src/modules/dashboard/components/end-day-select.tsx
  src/modules/dashboard/components/end-month-select.tsx
  src/modules/dashboard/components/end-year-select.tsx
  src/modules/dashboard/components/mandalart-card.tsx
  src/modules/dashboard/components/start-day-select.tsx
  src/modules/dashboard/components/start-month-select.tsx
  src/modules/dashboard/components/start-year-select.tsx
  src/modules/dashboard/hooks/.gitkeep
  src/modules/dashboard/hooks/use-create-room.ts
  src/modules/dashboard/hooks/use-delete-room.ts
  src/modules/dashboard/hooks/use-get-mandalart-cards.ts
  src/modules/dashboard/hooks/use-update-room-color.ts
  src/modules/dashboard/types/.gitkeep
  src/modules/dashboard/types/dashboard-type.ts
  src/modules/dashboard/util/calculate-date-differents.ts
  src/modules/dashboard/util/format-date.ts
  src/modules/dashboard/util/get-day-in-month.ts
  src/modules/guest/types/.gitkeep
  src/shared/utils/get-color-with-index.ts
Labels: 🔧Feature, 👨‍🔧Fix, 🏠Refactor, 💐Style

#149 Feature/#146 mandalart invite auth upgrade
  src/components/commons/drop-down.tsx
  src/components/ui/avatar.tsx
  src/modules/mandalart/components/mandalart-avatar-stack.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/mandalart-passcode-gate.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
  src/modules/mandalart/services/fetch-create-participants-user.ts
Labels: 🔧Feature, 💐Style

#155 bugfix:#86 방 참가 인원 ui버그 수정
  src/modules/dashboard/components/dashboard-avatar-stack.tsx
  src/modules/dashboard/components/mandalart-card.tsx
  tailwind.config.ts
Labels: 🕷️BugFix, 👨‍🔧Fix

#157 Bugfix/#153 헤더와 페이지 오류 해결
  src/app/today-list/loading.tsx
  src/components/layouts/header.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/today-list/components/today-todo-list.tsx
  src/modules/today-list/utils/flatten-todos.ts
Labels: 🕷️BugFix

#163 refactor:#161 alert 스위트알럿으로 교체
  src/modules/auth/hooks/use-auto-refresh-session.ts
  src/modules/auth/hooks/use-sign-up-form.ts
  src/modules/auth/hooks/use-update-password-form.ts
  src/modules/calendar/hooks/use-delete-todo-mutation.ts
  src/modules/calendar/hooks/use-update-todo-mutation.ts
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/dashboard.tsx
  src/modules/dashboard/hooks/use-delete-room.ts
  src/modules/dashboard/hooks/use-update-room-color.ts
  src/modules/mandalart/components/mandalart-passcode-gate.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
  src/shared/utils/sweet-alert.ts
Labels: 🏠Refactor

#159 Bugfix/#154 mandalart users store bugfix
  src/components/layouts/header.tsx
  src/modules/mandalart/components/mandalart-avatar-stack.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/realtime-cursors.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
  src/modules/mandalart/hooks/use-realtime-broadcast-room.ts
  src/modules/mandalart/hooks/use-realtime-cursors-room.ts
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
  src/modules/mandalart/hooks/use-users-store.ts
Labels: 🕷️BugFix, 🏠Refactor

#172 Chore/#171 github action을 위한 빌드 파일 수정
  .github/workflows/build_test.yml
Labels: 📜Chore

#162 Bugfix/#160 realtime cursor
  src/modules/mandalart/components/cursor.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/realtime-cursors.tsx
  src/modules/mandalart/hooks/use-realtime-cursors-room.ts
Labels: 🕷️BugFix, 🔧Feature

#158 Feature/#133 sentry
  src/app/(auth)/api/callback/route.ts
  src/app/(auth)/api/refresh/route.ts
  src/app/(auth)/api/sign-in/route.ts
  src/app/(non-auth)/guest/page.tsx
  src/app/api/dashboard/route.ts
  src/app/api/my-mandalarts/route.ts
  src/app/calendar/page.tsx
  src/app/hub/.gitkeep
  src/app/mandalart/[id]/page.tsx
  src/app/status/.gitkeep
  src/app/today-list/page.tsx
  src/components/layouts/header.tsx
  src/modules/auth/hooks/use-update-password-form.ts
  src/modules/auth/services/auth-server-service.ts
  src/modules/calendar/services/edit-todo-data.ts
  src/modules/dashboard/components/dashboard.tsx
  src/modules/dashboard/hooks/use-create-room.ts
  src/modules/dashboard/hooks/use-delete-room.ts
  src/modules/dashboard/hooks/use-update-room-color.ts
  src/modules/hub/components/.gitkeep
  src/modules/hub/hooks/.gitkeep
  src/modules/hub/services/.gitkeep
  src/modules/hub/types/.gitkeep
  src/modules/mandalart/components/users-info-sheet.tsx
  src/modules/mandalart/hooks/use-broadcast-mutation.ts
  src/modules/mandalart/hooks/use-get-room-data.ts
  src/modules/mandalart/hooks/use-todo-broadcast-mutation.ts
  src/modules/mandalart/services/fetch-check-room-passcode.ts
  src/modules/mandalart/services/fetch-create-participants-user.ts
  src/modules/mandalart/services/fetch-get-mandalarts-data.ts
  src/modules/mandalart/services/fetch-update-room-passcode.ts
  src/modules/status/components/.gitkeep
  src/modules/status/hooks/.gitkeep
  src/modules/status/services/.gitkeep
  src/modules/status/types/.gitkeep
  src/shared/hooks/use-get-my-mandalarts-query.ts
Labels: 🔧Feature

#168 bugfix:#92 투두를 생성하지 않았을 시 발생하는 오류 해결
  src/modules/today-list/components/today-todo-list.tsx
Labels: 🕷️BugFix

#176 fix:#174 로그인 폼에서 오류 메시지 표시 추가
  src/modules/auth/components/sign-in-form.tsx
Labels: 👨‍🔧Fix

#169 Feature/#86 selector 기본 값 --- 명시
  src/modules/dashboard/components/end-day-select.tsx
  src/modules/dashboard/components/end-month-select.tsx
  src/modules/dashboard/components/end-year-select.tsx
  src/modules/dashboard/components/start-day-select.tsx
  src/modules/dashboard/components/start-month-select.tsx
  src/modules/dashboard/components/start-year-select.tsx
Labels: 📜Chore

#170 Feature/#148 create my page
  src/app/(auth)/api/avatar/route.ts
  src/components/commons/button.tsx
  src/components/commons/text.tsx
  src/components/layouts/header.tsx
  src/modules/auth/actions/sign-out-action.ts
  src/modules/auth/actions/user-profile-action.ts
  src/modules/auth/components/profile/avatar-ui.tsx
  src/modules/auth/components/profile/nickname-ui.tsx
  src/modules/auth/components/profile/profile.tsx
  src/modules/auth/components/sign-out-button.tsx
  src/modules/auth/services/user-profile-service.ts
Labels: 🔧Feature

#181 Bugfix:#179 플로팅시트 높이 문제 해결
  src/components/commons/floating-sheet.tsx
Labels: 🕷️BugFix

#185 bugfix:#183 대주제 플로팅시트 클릭시 미작성 ui나오는 버그 수정
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
Labels: 🕷️BugFix

#187 feature:#186 사이트 나갈 때 물어보는 기능 추가
  src/app/(non-auth)/guest/page.tsx
  src/shared/hooks/use-on-before-unload.ts
Labels: 🔧Feature

#194 Feature/#189 upgrade layout
  src/app/layout.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
Labels: 🔧Feature, 💐Style

#202 Feature/#192 dashboard domain advanced
  src/components/commons/button.tsx
  src/components/commons/modal-portal.tsx
  src/modules/dashboard/components/calendar-drop-down.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
  src/modules/dashboard/components/create-mandalart-modal.tsx
  src/modules/dashboard/components/dashboard.tsx
  src/modules/dashboard/components/date-unit-select.tsx
  src/modules/dashboard/components/end-day-select.tsx
  src/modules/dashboard/components/end-month-select.tsx
  src/modules/dashboard/components/end-year-select.tsx
  src/modules/dashboard/components/mandalart-card.tsx
  src/modules/dashboard/components/start-day-select.tsx
  src/modules/dashboard/components/start-month-select.tsx
  src/modules/dashboard/components/start-year-select.tsx
  src/modules/dashboard/hooks/use-date-option-list.ts
  src/modules/dashboard/hooks/use-get-out-room.ts
  src/modules/dashboard/hooks/use-mandalart-creator.ts
  src/modules/dashboard/hooks/use-mandalart-form.ts
  src/modules/dashboard/hooks/use-room-date-update.ts
  src/modules/dashboard/types/dashboard-type.ts
  src/modules/dashboard/util/calculate-date.ts
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/shared/utils/sweet-alert.ts
  tailwind.config.ts
Labels: 📁Add, 🕷️BugFix, 🧹Clean Up, 🔧Feature, 🏠Refactor, 💐Style, 🚀 Performance

#196 feature:#195 esc 클릭 시 플로팅 시트가 꺼지는 커스텀 훅 생성
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/shared/hooks/use-escape-key.ts
Labels: 🔧Feature

#207 Refactor/#193 mandalart upgrade ux
  src/components/commons/floating-sheet.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/realtime-cursors.tsx
  src/modules/mandalart/components/todo-date-selector.tsx
  src/modules/mandalart/components/todo-item.tsx
  src/modules/mandalart/components/topic-group.tsx
  src/modules/mandalart/components/users-info-sheet.tsx
  src/modules/mandalart/hooks/use-realtime-cursors-room.ts
  src/modules/mandalart/services/create-new-todo-row-value.ts
Labels: 🔧Feature, 🏠Refactor, 💐Style

#201 Fix/#198 social login zod
  src/modules/auth/components/google-login-button.tsx
  src/modules/auth/components/kakao-login-button.tsx
Labels: 👨‍🔧Fix

#210 style/#204 버튼 및 입력 컴포넌트 스타일 수정 및 통합
  src/components/commons/button.tsx
  src/components/commons/input.tsx
  src/modules/auth/components/profile/nickname-ui.tsx
  src/modules/auth/components/profile/profile.tsx
  src/modules/auth/components/sign-out-button.tsx
Labels: 💐Style

#203 Style/#200 refactor auth page css
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/layout.tsx
  src/modules/auth/components/sign-in-form.tsx
  src/modules/auth/components/sign-up-form.tsx
  src/shared/constants/auth-schema.ts
Labels: 👨‍🔧Fix, 💐Style

#214 Feature/#213 input max length
  src/modules/dashboard/components/create-mandalart-modal.tsx
  src/modules/guest/components/guest-mandalart-block.tsx
  src/modules/guest/components/guest-mandalart-cell.tsx
  src/modules/guest/components/guest-mandalart-main-block.tsx
  src/modules/guest/components/guest-mandalart-main-cell.tsx
Labels: 🔧Feature

#215 Refactor/#197 calendar todo
  src/app/layout.tsx
  src/components/commons/drop-down.tsx
  src/components/layouts/header.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/today-list/components/mandalart-title-tab.tsx
  src/modules/today-list/components/order-option-selection.tsx
  src/modules/today-list/components/today-todo-list.tsx
  src/modules/today-list/components/todo-item.tsx
  src/modules/today-list/types/today-list-type.ts
  src/modules/today-list/utils/flatten-todos.ts
  src/styles/calendar-custom.css
Labels: 🕷️BugFix, 🔧Feature, 💐Style

#217 Style/#216 header
  src/app/layout.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
Labels: 💐Style

#205 feature:#192 피드백 수용
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
  src/modules/dashboard/components/create-mandalart-modal.tsx
  src/modules/dashboard/components/dashboard.tsx
  src/modules/dashboard/util/calculate-date.ts
  src/modules/dashboard/util/format-date.ts
  src/shared/utils/get-color-with-index.ts
Labels: 🕷️BugFix

#165 Feature/#164 bottom sheet
  package.json
  pnpm-lock.yaml
  src/components/commons/floating-sheet.tsx
  src/components/layouts/header.tsx
  src/components/ui/drawer.tsx
  src/modules/calendar/components/calendar-floating-sheet.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/mandalart/components/core-cell.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/sub-topic-cell.tsx
  src/modules/mandalart/components/topic-cell.tsx
  src/modules/mandalart/hooks/use-realtime-cursors-room.ts
  src/modules/mandalart/hooks/use-todo-floating-sheet-store.ts
  src/shared/hooks/use-floating-sheet-store.ts
Labels: 🔧Feature, 💐Style

#228 feature:#226 오픈그래프 설정
  public/images/open-graph/opengraph.png
  src/app/layout.tsx
Labels: 🔧Feature

#221 feature:#220 만다라트 편집 인원 수 제한 기능 추가, 설정한 인원 넘어가면 홈으로 리다이렉션
  src/modules/mandalart/components/mandalart-avatar-stack.tsx
  src/modules/mandalart/hooks/use-realtime-presence-room.ts
Labels: 🔧Feature

#223 Bugfix/#192 대시보드 모달 중첩 현상 제거
  src/app/dashboard/page.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
Labels: 🕷️BugFix

#230 Feature/#224 guest canvas feature
  package.json
  pnpm-lock.yaml
  src/app/(non-auth)/guest/page.tsx
  src/modules/guest/components/guest-modal.tsx
  src/modules/guest/components/guest-navigation.tsx
  src/modules/guest/hooks/use-download-mandalart.tsx
  src/shared/hooks/use-canvas-controller.tsx
Labels: 🔧Feature, 🏠Refactor

#219 Fix/#211 profile advance
  src/app/(auth)/api/callback/route.ts
  src/app/layout.tsx
  src/components/commons/button.tsx
  src/components/commons/input.tsx
  src/components/commons/text.tsx
  src/components/layouts/header.tsx
  src/modules/auth/components/profile/avatar-ui.tsx
  src/modules/auth/components/profile/nickname-ui.tsx
  src/modules/auth/components/profile/profile.tsx
  src/modules/auth/components/profile/user-avatar-card.tsx
  src/modules/auth/services/user-profile-service.ts
  src/shared/utils/avatar-utils.ts
  tailwind.config.ts
Labels: 🕷️BugFix, 🔧Feature, 👨‍🔧Fix, 💐Style

#236 feature:#235 로딩 스피너 제작
  public/images/loading/flower1.svg
  public/images/loading/flower2.svg
  public/images/loading/flower3.svg
  public/images/loading/seed1.svg
  public/images/loading/seed2.svg
  public/images/loading/seed3.svg
  public/images/loading/sprout1.svg
  public/images/loading/sprout2.svg
  public/images/loading/sprout3.svg
  src/components/commons/animation-loading-ui.tsx
  src/components/commons/loading-spinner.tsx
Labels: 🔧Feature

#234 bugfix:#231 공백 영역 스크롤 안되는 문제 해결
  src/styles/globals.css
Labels: 🕷️BugFix

#229 Feature/#209 mandalart ai suggestion
  public/images/button-image/ai.svg
  src/app/api/mandalart/route.ts
  src/components/commons/alert.tsx
  src/modules/mandalart/components/ai-suggest-button.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/hooks/use-get-ai-usage-count-query.ts
  src/modules/mandalart/hooks/use-usage-count-mutations.ts
  src/modules/mandalart/services/fetch-get-ai-suggest-keywords.ts
  src/modules/mandalart/services/fetch-get-ai-usage-count.ts
  src/modules/mandalart/services/fetch-post-ai-usage-count.ts
  src/modules/mandalart/services/fetch-update-room-passcode.ts
  src/shared/hooks/use-alert-store.ts
Labels: 🔧Feature, 💐Style

#239 Feature/#232 topics done check
  src/components/commons/input.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/modules/mandalart/components/sub-topic-cell.tsx
  src/modules/mandalart/components/todo-item.tsx
Labels: 🔧Feature, 🏠Refactor, 💐Style

#241 Feature/#240 realtime mandalart canvas feature
  src/modules/mandalart/components/ai-suggest-button.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/hooks/use-download-realtime-mandalart.tsx
  src/shared/hooks/use-canvas-controller.tsx
Labels: 📜Chore, 🔧Feature, 💐Style

#245 Fix/#243 tailwind 변경에 따른 prefix 변경
  src/app/layout.tsx
  src/components/commons/input.tsx
  src/components/commons/progress-bar.tsx
  src/components/commons/round-button.tsx
  src/components/commons/text.tsx
  src/components/commons/title.tsx
  src/components/landing/intro-sercion.tsx
  src/modules/auth/components/sign-up-form.tsx
  src/modules/dashboard/components/card-button-drop-down.tsx
  src/modules/dashboard/components/category-board.tsx
  src/modules/dashboard/components/dashboard-avatar-stack.tsx
  src/modules/guest/components/guest-mandalart-block.tsx
  src/modules/guest/components/guest-mandalart-main-block.tsx
  src/modules/mandalart/components/todo-day-select.tsx
  src/modules/mandalart/components/todo-month-select.tsx
  src/modules/mandalart/components/todo-year-select.tsx
  tailwind.config.ts
Labels: 👨‍🔧Fix, 💐Style

#246 feature:#244 사이트맵 생성 로직 구현
  src/app/layout.tsx
  src/app/sitemap.ts
Labels: 📁Add, 🔧Feature

#251 Style/#248 calendar todo
  src/app/calendar/page.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/today-list/components/order-option-selection.tsx
  src/styles/calendar-custom.css
Labels: 💐Style

#253 Update README.md
  README.md
Labels: 📝 Documentation

#259 feature:#258 만다라트 페이지 안내 모달 추가
  public/images/mandalart/instruction-guide.png
  src/modules/mandalart/components/instruction-modal.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/user-navigation.tsx
Labels: 🔧Feature

#261 chore:#248 버튼 삭제
  src/modules/today-list/components/order-option-selection.tsx
Labels: 👨‍🔧Fix

#260 Bugfix/#249 mandalart input bugfix
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
Labels: 🕷️BugFix, 🏠Refactor

#254 feature:#235 로딩 페이지 추가
  src/app/loading.tsx
  src/app/mandalart/[id]/page.tsx
  src/modules/calendar/components/mandalart-calendar.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/hooks/use-batch-update-trigger.ts
  src/modules/today-list/components/today-todo-list.tsx
Labels: 🔧Feature

#262 Chore/#256 version up
  package.json
Labels: 📜Chore

#268 Bugfix/#256 1.0.1 버전 배포
  package.json
  src/app/(non-auth)/guest/page.tsx
  src/modules/mandalart/components/instruction-modal.tsx
  src/modules/mandalart/components/main-block.tsx
  src/modules/mandalart/components/mandalart-floating-sheet.tsx
  src/modules/mandalart/components/mandalart-main-content.tsx
  src/modules/mandalart/components/sub-block.tsx
  src/shared/utils/get-color-with-number.ts
Labels: 🕷️BugFix

#273 [Chore] 버저닝 관리 및 배포 1.0.2
  package.json
  src/app/layout.tsx
  src/components/commons/round-button.tsx
  src/modules/mandalart/hooks/use-mandalart-data-query.ts
Labels: 📜Chore
